FROM ubuntu:focal
RUN apt-get update \
    && apt-get install -y libreoffice \
    && rm -rf /var/lib/apt/lists/*
EXPOSE 2002
CMD [ "soffice",            \
    "--headless",           \
    "--invisible",          \
    "--nocrashreport",      \
    "--nodefault",          \
    "--nofirststartwizard", \
    "--nologo",             \
    "--norestore",          \
    "--accept=socket,host=0.0.0.0,port=2002,tcpNoDelay=1;urp;StarOffice.ComponentContext" \
]
